#Docker compose for EBS Linux Platform 2
version: "3"
services:
    client:
        image: "mrmasson/complex-client"
        mem_limit: 128m
        hostname: client
    server:
        image: "mrmasson/complex-server"
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: "mrmasson/complex-worker"
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    nginx:
        image: "mrmasson/complex-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
            - "80:80"
