apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: yourdomain-com-tls
spec:
    secretName: yourdomain-com
    issuerRef:
        # The name of the issuer metadata name
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: yourdomain.com
    dnsNames:
        - yourdomain.com
        - www.yourdomain.com
